

class RandomGenerator{
	constructor(min, max){ 
		//takes in the minimum and maximum values
		this.min = min;
		this.max = max;
		this.randomNumber = null;
		//if they are not defined, it sets the minimum to 1, and the max to 10
		if (min === undefined) {
			this.min = 1
		}
		if (max === undefined) {
			this.max = 10
		}
		//makes storage for the random number
		

	}
	generate(){
		//make a random value between the minimum and maximum values
		this.randomNumber = Math.floor(Math.random() * (this.max - this.min + 1) + this.min);
		console.log('Random Number', this.randomNumber);
		//and store the number into the storage from the constructor

	}
	getRange(){
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
	}
	getNum(){
		//return the random number that was generated by generate()
	}
}

const test = new RandomGenerator(1, 10);